---
# Ansible playbook to perform create/delete operation of bridge domain
#
#@header_start
# "mop_version": "1.0.0"
# "name": "Create/Delete Bridge domain on a XE router"
# "description": "Create/Delete Bridge domain on a XE router"
# "pb_params_sample_file_name": "router_config_bridge_domain_params.json"
# "pb_params_spec_file_name": "router_config_bridge_domain_specs.json"
# "long_description": "This playbook is to create or delete the bridge domain"
# "sw_platform": "IOS XE,IOS"
# "min_nodes": 1
# "max_nodes": 1
#@header_end


##############################################################################
# Maintenance phase
##############################################################################
- name: Perform Lock on the devices
  hosts: localhost
  any_errors_fatal: true
  connection: local
  gather_facts: no
  vars:
    - router_ip: "{{ inventory_hostname }}"
    - router_name: "{{ hosts }}"
    - check_mode: "{{ check_mode }}"

  roles:
    - { role: router_op_dlm_node_lock, tags: ["maintenance"] }

- name: Create/Delete Bridge domain on a XE router
  hosts: "{{ hosts }}"
  any_errors_fatal: true
  connection: local
  gather_facts: no
  vars:
    - router_ip: "{{ inventory_hostname }}"
    - router_name: "{{ hosts }}"
    - unique_id: "on a XE router"
    - bridge_domain_list: "{{ bridge_domain_list }}"
    - operation: "{{ operation }}"

  roles:
    - { role: router_config_bridge_domain, tags: ["maintenance"] }
