---
# Playbook to delete the bgp neighbors on a router
# Revanth Nayanavari (rnayanav@cisco.com)
# 11/12/2017
#
#@header_start
# "mop_version": "1.0.0"
# "name": "Delete bgp neighbors on a router"
# "description": "Delete bgp neighbors on a router"
# "pb_params_sample_file_name": "router_config_delete_bgp_neighbors_params.json"
# "pb_params_spec_file_name": "router_config_delete_bgp_neighbors_specs.json"
# "prerequisites": "If BGP instance specified in params doesnt exist on router, playbook fails.<br />If vrf is specified in params but the same is not configured under BGP on router, the playbook fails"
# "long_description": "This playbook deletes one or more BGP neighbors on a router."
# "sw_platform": "IOS XR"
# "min_nodes": 1
# "max_nodes": 1
#@header_end


- name: Perform Lock on the devices
  hosts: localhost
  any_errors_fatal: true
  connection: local
  gather_facts: no
  vars:
    - router_ip: "{{ inventory_hostname }}"
    - router_name: "{{ hosts }}"
    - check_mode: "{{ check_mode }}"

  roles:
    - { role: router_op_dlm_node_lock, tags: ["maintenance"] }

- name: Delete bgp neighbors on a router
  hosts: "{{ hosts }}"
  any_errors_fatal: true
  connection: local
  gather_facts: no
  vars:
    - router_ip: "{{ inventory_hostname }}"
    - check_mode: "{{ check_mode }}"

  roles:
    - { role: router_config_delete_bgp_neighbors, tags: ["maintenance"] }

...
