# Playbook to create/update/delete VRF on the designated router
# akuriako@cisco.com
# 9/19/2017

#@header_start
# "mop_version": "1.0.0"
# "name": "Create/update/delete VRF configuration on a router"
# "description": "Creates a new VRF or updates/deletes an existing VRF config"
# "pb_params_sample_file_name": "router_config_vrf_params.json"
# "pb_params_spec_file_name": "router_config_vrf_specs.json"
# "long_description": "Creates a new VRF or updates/deletes an existing VRF config. The entire VRF will be deleted with ‘delete’ operation"
# "sw_platform": "IOS XR"
# "min_nodes": 1
# "max_nodes": 1
#@header_end

##############################################################################
# Pre-Maintenance phase
##############################################################################

##############################################################################
# Maintenance phase
##############################################################################
- name: Perform Lock on the devices
  hosts: localhost
  any_errors_fatal: true
  connection: local
  gather_facts: no
  vars:
    - router_ip: "{{ inventory_hostname }}"
    - router_name: "{{ hosts }}"
    - check_mode: "{{ check_mode }}"

  roles:
    - { role: router_op_dlm_node_lock, tags: ["maintenance"] }

- name: Create/update/delete VRF config on a router
  hosts: "{{ hosts }}"
  connection: local
  gather_facts: no
  any_errors_fatal: true

  vars:
    - router_ip: "{{ inventory_hostname }}"
    - check_mode: "{{ check_mode }}"
    - operation: "{{ operation }}"
    - vrf_name: "{{ vrf_name }}"
    - vrf_addressfamily: "{{ vrf_addressfamily }}"

  roles:
    - { role: router_config_vrf, tags: ["maintenance"] }
##############################################################################
# Post-Maintenance phase
##############################################################################
