---
# Playbook to remove interface from bunle-ether and delete the bundle-ether on the designated router pair
#
#@header_start
# "mop_version": "1.0.0"
# "name": "Remove interface from Bundle Ether and delete bundle-ether"
# "description": "Remove interface from Bundle Ether and delete the bundle on 2 routers"
# "pb_params_sample_file_name": "router_config_delete_bundle_ether_params.json"
# "pb_params_spec_file_name": "router_config_delete_bundle_ether_specs.json"
# "prerequisites": "The interface(s) being removed from bundle should be part of the bundle."
# "long_description": "This playbook deletes interface(s) from a bundle on the given routers. It also deletes the bundle."
# "sw_platform": "IOS XR"
# "min_nodes": 2
# "max_nodes": 2
#@header_end

#########################################################
# Maintenance phase
#########################################################
- name: Perform Lock on the devices
  hosts: localhost
  any_errors_fatal: true
  connection: local
  gather_facts: no
  vars:
    - router_ip: "{{ inventory_hostname }}"
    - router_name: "{{ hosts }}"
    - check_mode: "{{ check_mode }}"

  roles:
    - { role: router_op_dlm_node_lock, tags: ["maintenance"] }

- name: Delete interface(s) from Bundle-Ether on router1
  hosts: "{{ rtr1_host }}"
  connection: local
  gather_facts: no
  any_errors_fatal: true

  vars:
    - router_ip: "{{ inventory_hostname }}"
    - unique_id: "on router1"
    - bundle_id: "{{ rtr1_bundle_id }}"
    - interfaces: "{{ rtr1_interfaces }}"
    - operation: "remove"
  roles:
    - { role: router_config_modify_interface_bundle_ether,  tags: ["maintenance"] }


- name: Delete Bundle-Ether on router1
  hosts: "{{ rtr1_host }}"
  connection: local
  gather_facts: no
  any_errors_fatal: true

  vars:
    - router_ip: "{{ inventory_hostname }}"
    - unique_id: "on router1"
    - bundle_id: "{{ rtr1_bundle_id }}"
  roles:
    - { role: router_config_delete_bundle_ether,  tags: ["maintenance"] }

- name: Delete interface(s) from Bundle-Ether on router2
  hosts: "{{ rtr2_host }}"
  connection: local
  gather_facts: no
  any_errors_fatal: true

  vars:
    - router_ip: "{{ inventory_hostname }}"
    - unique_id: "on router2"
    - bundle_id: "{{ rtr2_bundle_id }}"
    - interfaces: "{{ rtr2_interfaces }}"
    - operation: "remove"
  roles:
    - { role: router_config_modify_interface_bundle_ether,  tags: ["maintenance"] }

- name: Delete a Bundle-Ether on router2
  hosts: "{{ rtr2_host }}"
  connection: local
  gather_facts: no
  any_errors_fatal: true

  vars:
    - router_ip: "{{ inventory_hostname }}"
    - unique_id: "on router2"
    - bundle_id: "{{ rtr2_bundle_id }}"
  roles:
    - { role: router_config_delete_bundle_ether,  tags: ["maintenance"] }

...
