---
# Playbook to check whether an interface is configured with specified ipv4 address
#@header_start
# "mop_version": "1.0.0"
# "name": "Check whether given interface is configured with specified ipv4 address on the router"
# "description": "Check whether given interface is configured with specified ipv4 address on the router"
# "pb_params_sample_file_name": "router_check_ipv4_interface_address_params.json"
# "pb_params_spec_file_name": "router_check_ipv4_interface_address_specs.json"
# "long_description": "This playbook is to check if the given interface is configured with the given IPV4 address. The playbook would fail otherwise"
# "sw_platform": "IOS XE,IOS"
# "min_nodes": 1
# "max_nodes": 1
#@header_end

##############################################################################
# Maintenance phase
##############################################################################
- name: Perform Lock on the devices
  hosts: localhost
  any_errors_fatal: true
  connection: local
  gather_facts: no
  vars:
    - router_ip: "{{ inventory_hostname }}"
    - router_name: "{{ hosts }}"
    - check_mode: "{{ check_mode }}"

  roles:
    - { role: router_op_dlm_node_lock, tags: ["maintenance"] }

- name: Check IP address of the interface
  hosts: "{{ hosts }}"
  connection: local
  gather_facts: no
  any_errors_fatal: true
  vars:
    - router_ip: "{{ inventory_hostname }}"
    - router_name: "{{ hosts }}"
    - if_name: "{{ if_name }}"
    - ip_address: "{{ ip_address }}"
    - source: astack
    - check: "ipv4_interface_address"

  roles:
    - { role: router_check, tags: ["maintenance"] }
...
