---
# Playbook to create/delete the static routes on a router
# Revanth Nayanavari (rnayanav@cisco.com)
# 09/10/2017
#
#@header_start
# "mop_version": "1.0.0"
# "name": "Create/Delete static routes on a router"
# "description": "Create/Delete static routes on a router"
# "pb_params_sample_file_name": "router_config_static_route_params.json"
# "pb_params_spec_file_name": "router_config_static_route_specs.json"
# "prerequisites": "To create VRF static route, the VRF should be existing on the device."
# "long_description": "This playbook takes a list of static routes as input and either creates or deletes the list in the router in global or VRF mode,  depending on the parameter 'operation'"
# "sw_platform": "IOS XR,IOS XE,IOS"
# "sw_version": "6.1.1"
# "hw_platform": "NCS5500"
# "min_nodes": 1
# "max_nodes": 1
#@header_end

- name: Perform Lock on the devices
  hosts: localhost
  any_errors_fatal: true
  connection: local
  gather_facts: no
  vars:
    - router_ip: "{{ inventory_hostname }}"
    - router_name: "{{ hosts }}"
    - check_mode: "{{ check_mode }}"

  roles:
    - { role: router_op_dlm_node_lock, tags: ["maintenance"] }

- name: Create/Delete static routes on a router
  hosts: "{{ hosts }}"
  any_errors_fatal: true
  connection: local
  gather_facts: no
  vars:
    - router_ip: "{{ inventory_hostname }}"
    - check_mode: "{{ check_mode }}"

  roles:
    - { role: router_config_static_route, tags: ["maintenance"] }

...
