---
# Playbook to add/remove VRF on a bgp on the designated router
#
#@header_start
# "mop_version": "1.0.0"
# "name": "Add/remove VRF under BGP on a router"
# "description": "Add/remove VRF under BGP on a router"
# "pb_params_sample_file_name": "router_config_bgp_vrf_params.json"
# "pb_params_spec_file_name": "router_config_bgp_vrf_specs.json"
# "prerequisites": "BGP with the instance specified in 'bgp_id' param should be configured on router. <br />For the add operation, there should not be any VRF configured by the name specified in 'vrf_name' param under BGP.<br />For 'delete' operation, the VRF by name specified in 'vrf_name' param should exist under BGP. If not, the playbook fails."
# "long_description":"This playbook creates/deletes a BGP VRF on a router. "
# "sw_platform": "IOS XR"
# "min_nodes": 1
# "max_nodes": 1
#@header_end


##############################################################################
# Maintenance phase
##############################################################################
- name: Perform Lock on the devices
  hosts: localhost
  any_errors_fatal: true
  connection: local
  gather_facts: no
  vars:
    - router_ip: "{{ inventory_hostname }}"
    - router_name: "{{ hosts }}"
    - check_mode: "{{ check_mode }}"

  roles:
    - { role: router_op_dlm_node_lock, tags: ["maintenance"] }

- name: Add/remove VRF under BGP on a router
  hosts: "{{ hosts }}"
  connection: local
  gather_facts: no
  any_errors_fatal: true

  vars:
    - unique_id: "on a router"
    - router_ip: "{{ inventory_hostname }}"
    - operation: "{{ operation }}"
  roles:
    - { role: router_config_bgp_vrf, tags: ["maintenance"]}

...
