---
# Playbook to delete prefix set on the designated router

#@header_start
# "mop_version": "1.0.0"
# "name": "Prefix Set Delete"
# "description": "Delete prefixes from the given prefix_set or the prefix_set itself"
# "pb_params_sample_file_name": "router_config_prefix_set_delete_params.json"
# "pb_params_spec_file_name": "router_config_prefix_set_delete_specs.json"
# "long_description": "List of prefixes to be deleted from the set"
# "sw_platform": "IOS XR"
# "min_nodes": 1
# "max_nodes": 1
#@header_end

##############################################################################
# Pre-Maintenance phase
##############################################################################

##############################################################################
# Maintenance phase
##############################################################################
- name: Perform Lock on the devices
  hosts: localhost
  any_errors_fatal: true
  connection: local
  gather_facts: no
  vars:
    - router_ip: "{{ inventory_hostname }}"
    - router_name: "{{ hosts }}"
    - check_mode: "{{ check_mode }}"

  roles:
    - { role: router_op_dlm_node_lock, tags: ["maintenance"] }

- name: Delete prefixes from prefix-set or delete prefix-set on specified router
  hosts: "{{ hosts }}"
  connection: local
  gather_facts: no
  any_errors_fatal: true

  vars:
    - router_ip: "{{ inventory_hostname }}"

  roles:
    - { role: router_config_prefix_set_delete, tags: ["maintenance"]}

##############################################################################
# Post-Maintenance phase
##############################################################################
...
