---
# Ansible playbook to perform basic cpu usage checks to a router
#@header_start
# "mop_version": "1.0.0"
# "name": "Check cpu usage of the router"
# "description": "Check cpu usage percentage on a router"
# "pb_params_sample_file_name": "router_check_cpu_proc_params.json"
# "pb_params_spec_file_name": "router_check_cpu_proc_specs.json"
# "long_description": "This playbook is to check the CPU usage of the device. The playbook fails if the CPU utilization is higher than the given CPU threshold precentage"
# "sw_platform": "IOS XE,IOS" 
# "min_nodes": 1
# "max_nodes": 1
#@header_end


#########################################################
# Maintenance phase
#########################################################
- name: Perform Lock on the devices
  hosts: localhost
  any_errors_fatal: true
  connection: local
  gather_facts: no
  vars:
    - router_ip: "{{ inventory_hostname }}"
    - router_name: "{{ hosts }}"
    - check_mode: "{{ check_mode }}"

  roles:
    - { role: router_op_dlm_node_lock, tags: ["maintenance"] }

- name: Check cpu usage of a router
  hosts: "{{ hosts }}"
  any_errors_fatal: true
  connection: local
  gather_facts: no
  vars:
    - router_ip: "{{ inventory_hostname }}"
    - router_name: "{{ hosts }}"
    - source: astack
    - unique_id: "on a router"
    - cpu_threshold_percentage: "{{ cpu_threshold_percentage }}"
    - check: "cpu_proc"

  roles:
    - { role: router_check, tags: ["maintenance"] }
